spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: talents
    password: talents!2021
    # spring2.0此处为jdbc-url
    url: jdbc:mysql://192.168.1.175:23306/talents?useUnicode=true&characterEncoding=utf-8&useSSL=false

